### ISSUE TITLE
maven doc review

### ISSUE THREAD

**Issue by sahoob** [CTS-DEVOPS/class_notes#2]
doc reviewd by - Bibhu

**Comment by sahoob** [comment]
review  still inprogress

**Comment by vipulkabra** [comment]
when can have review completed?

**Comment by sahoob** [comment]
HI Vipul Sir - review done . please can you close the issue ??

**Comment by Narwade** [comment]
no please wait, give me proof that its resolved

**Comment by sahoob** [comment]
Issue has been assigened to Ashwini to provide SME signoff, post which this can be close.

**Comment by ashwanichamp** [comment]
looks good to me!!!!

**Comment by vipulkabra** [comment]
ok closing the issue
